sudo: false
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - android-22
    - sys-img-armeabi-v7a-android-22
before_install:
  - yes | sdkmanager "platforms;android-25"
  - yes | sdkmanager "build-tools;25.0.3"
before_script:
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
script:
  - ./gradlew build check
  - ./gradlew connectedAndroidTest coveralls